language: python
python:
  - 2.7
before_script:
    - psql -c 'create database tdjangotest;' -U postgres
    - ./manage_test.py makemigrations
    - ./manage_test.py migrate
install:
    - pip install .
services:
    - postgresql
script:
    - trial tdjango
